src/objects/Answer__c.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Answer</label>
    <nameField>
        <displayFormat>A-{00}</displayFormat>
        <label>Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Product_Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Product Group</label>
        <referenceTo>Product_Group__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Product_Group__c.object
<CustomObject>
    <label>Product Group</label>
    <nameField>
        <label>Product Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Question__c.object
<CustomObject>
    <fields>
        <fullName>Product_Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Product Group</label>
        <referenceTo>Product_Group__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Textarea</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Picklist</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Values__c</fullName>
        <label>Values</label>
        <type>TextArea</type>
    </fields>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{00}</displayFormat>
        <label>Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TBN_CaptureAnswerController.cls
public with sharing class TBN_CaptureAnswerController {
	public TBN_CaptureAnswerController()
    {
        
    
    }
    
    public class cNodes
    {
    
     public List<Question__c> parent {get; set;}
     Public Product2 gparent {get;set;}
    
     public cNodes(string gp, List<Question__c> p)
     {
         parent = p;
         gparent = [Select Id,Name from product2 where id = :gp limit 1];
     }
    }
     
    
    Public List<cNodes> hierarchy;
    
    Public List<cNodes> getmainnodes()
    {
        hierarchy = new List<cNodes>();
        List<product2 > tempparent = [Select Id,Name,Product_Group__c from product2 ];
        
          set<string> setProductGp = new set<string>();
          for(product2 obj:tempparent )
          {
          if(obj.Product_Group__c != null)
          setProductGp .add(obj.Product_Group__c );
          }
         List<Question__c> tempchildren = [Select Id,Product_Group__c,Type__c  ,Values__c,Name,(Select Id,name from Answers__r) from Question__c where Product_Group__c IN :setProductGp ];
         map<string, List<Question__c>> mapToStore = new map<string, List<Question__c>>();
         
         
         List<Question__c> tempchildrenTwo = new list<Question__c>();
         
         for( Question__c onjQues :tempchildren )
         {
             
            tempchildrenTwo = new list<Question__c>();                           
            if(mapToStore.containsKey(onjQues.Product_Group__c  ))
            {   
                tempchildrenTwo = mapToStore.get(onjQues.Product_Group__c  ); 
            }
           
           
            tempchildrenTwo.add(onjQues);
            mapToStore.put(onjQues.Product_Group__c  , tempchildrenTwo);
            
         }
         
         for(product2 objprod : tempparent )
         {
             if(objprod .Product_Group__c != null)
             hierarchy.add(new cNodes(objprod .id,mapToStore.get(objprod.Product_Group__c   ) ));
         }
         
        return hierarchy;
    }  
}